// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: consignment.proto

package consignment_proto

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

// Encoders

// Handlers

// Decoders

//Streams

// RegisterConsignmentServiceOrionServer registers ConsignmentService to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterConsignmentServiceOrionServer(sf interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&_ConsignmentService_serviceDesc, sf)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterConsignmentServiceDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "ConsignmentService", encoder)
}

// DefaultDecoder
func RegisterConsignmentServiceDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "ConsignmentService", decoder)
}

