// Code generated by protoc-gen-orion. DO NOT EDIT.
// source: consignment.proto

package consignment_proto

import (
	orion "github.com/carousell/Orion/orion"
)

// If you see error please update your orion-protoc-gen by running 'go get -u github.com/carousell/Orion/protoc-gen-orion'
var _ = orion.ProtoGenVersion1_0

// Encoders

// Handlers

// Decoders

//Streams

// RegisterShippingServiceOrionServer registers ShippingService to Orion server
// Services need to pass either ServiceFactory or ServiceFactoryV2 implementation
func RegisterShippingServiceOrionServer(sf interface{}, orionServer orion.Server) error {
	err := orionServer.RegisterService(&_ShippingService_serviceDesc, sf)
	if err != nil {
		return err
	}

	return nil
}

// DefaultEncoder
func RegisterShippingServiceDefaultEncoder(svr orion.Server, encoder orion.Encoder) {
	orion.RegisterDefaultEncoder(svr, "ShippingService", encoder)
}

// DefaultDecoder
func RegisterShippingServiceDefaultDecoder(svr orion.Server, decoder orion.Decoder) {
	orion.RegisterDefaultDecoder(svr, "ShippingService", decoder)
}

